services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root1234"
      POSTGRES_DB: "notenoughdb"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root1234"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin-data:/pgadmin/

  api:
    build:
      context: .
    environment:
      - ConnectionStrings__Postgres_Db=Server=db;Database=notenoughdb;Port=5432;Username=admin;Password=root1234
    ports:
      - "8080:80"
    expose:
    - "8080"
    depends_on:
      - db